# Generated by Django 5.1.5 on 2025-01-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hookrequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
